// Test broker data for comparison tool
import { Broker } from '@/lib/database-types';

export const testBrokers: Broker[] = [
  {
    id: 'test-broker-1',
    name: 'eToro',
    country: 'Cyprus',
    regulations: 'CySEC, FCA, ASIC',
    min_deposit: 200,
    trading_fee: 0,
    logo_url: 'https://logo.clearbit.com/etoro.com',
    rating: 4.7,
    supported_assets: ['Forex', 'Stocks', 'Crypto', 'Commodities'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'test-broker-2',
    name: 'XM',
    country: 'Cyprus',
    regulations: 'CySEC, ASIC, IFSC',
    min_deposit: 5,
    trading_fee: 0,
    logo_url: 'https://logo.clearbit.com/xm.com',
    rating: 4.3,
    supported_assets: ['Forex', 'CFDs', 'Commodities'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'test-broker-3',
    name: 'Pepperstone',
    country: 'Australia',
    regulations: 'ASIC, FCA',
    min_deposit: 200,
    trading_fee: 0,
    logo_url: 'https://logo.clearbit.com/pepperstone.com',
    rating: 4.8,
    supported_assets: ['Forex', 'CFDs', 'Indices'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'test-broker-4',
    name: 'IC Markets',
    country: 'Australia',
    regulations: 'ASIC, CySEC',
    min_deposit: 200,
    trading_fee: 0,
    logo_url: 'https://logo.clearbit.com/icmarkets.com',
    rating: 4.6,
    supported_assets: ['Forex', 'CFDs', 'Crypto'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'test-broker-5',
    name: 'OANDA',
    country: 'USA',
    regulations: 'CFTC, FCA, ASIC',
    min_deposit: 0,
    trading_fee: 0,
    logo_url: 'https://logo.clearbit.com/oanda.com',
    rating: 4.5,
    supported_assets: ['Forex', 'CFDs'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'test-broker-6',
    name: 'Plus500',
    country: 'Israel',
    regulations: 'CySEC, FCA, ASIC',
    min_deposit: 100,
    trading_fee: 0,
    logo_url: 'https://logo.clearbit.com/plus500.com',
    rating: 4.2,
    supported_assets: ['CFDs', 'Forex', 'Crypto'],
    created_at: new Date().toISOString(),
  },
  {
    id: 'test-broker-7',
    name: 'Admiral Markets',
    country: 'Estonia',
    regulations: 'CySEC, FCA, ASIC',
    min_deposit: 100,
    trading_fee: 0,
    logo_url: 'https://logo.clearbit.com/admiralmarkets.com',
    rating: 4.4,
    supported_assets: ['Forex', 'CFDs', 'Stocks'],
    created_at: new Date().toISOString(),
  }
];
